version: 2.0
jobs:
 build:
   docker:
      - image: mcr.mcrosoft.com/dotnet/core/sdk:2.2
   steps:
     - checkout
     - run: dotnet restore
     - run: dotnet build
     - run: dotnet test --no-build CircleCITest
